### PR TITLE
Update dependencies and adds Dockerfile

### PR DESCRIPTION
**Pull request by emorozov**
There were too many errors when I tried to sync using the original dependencies from the repository. I guess newer exchangelib or/and caldav fixed some of the errors because after upgrade I was able to sync almost all calendar entries.

This also adds basic Dockerfile.

### CODE REVIEW

**Comment by mhthies** [comment]
Thanks for contributing this. :) 

Can you add a short description on how to use the Dockerfile / the resulting Docker container to the README file?

**Comment by emorozov** [comment]
Hello mhthies,
Thanks for the script - it's very helpful to me because I hate running Evolution just not to miss events from my calendar.

I've updated the pull request with GitHub Workflow that should build and publish docker image in your GitHub docker registry.

I'm new to GitHub CI/CD but that workflow worked just fine in my repository without any prior setup.

Also added instructions to the README on how to run the script via docker.

**Comment by emorozov** [comment]
Note: maybe you'll need to create a personal token in order for image publish job to work. I'm not 100% sure as I was following some tutorials and created the personal access token first. There're many online tutorials on how to do it, e.g.:
https://earthly.dev/blog/streamline-container-ghcr/

**Comment by emorozov** [comment]
@mhthies Hello, can you please take a look on the updated pull request, please?

**Pull request merged**
